### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [micaelacancino/DulceTentacion#23]
## Proceso

1. Ingrese a la pagina.
2. Navegue por las distintas secciones.

## Resultado esperado

• Que todas las secciones cuenten con el logo.

## Resultado actual

• Solo la pagina principal/Home cuenta con el logo.

## Captura

![image](https://github.com/user-attachments/assets/b66905b6-9991-4f7c-b81f-c4df1fbdcdb0)
![image](https://github.com/user-attachments/assets/59506d84-16bb-4eef-912c-2e3ec2d0c2d3)
![image](https://github.com/user-attachments/assets/6cb48335-278b-45cf-9cc6-100ceffa4da4)
![image](https://github.com/user-attachments/assets/b7d70d54-ccb8-4d36-acf1-eb2d5dda365a)
![image](https://github.com/user-attachments/assets/031e1568-08aa-4dfd-b6de-6f0b1c6f674d)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by micaelacancino** [comment]
Buenas tardes, ya realizamos la corrección.
