### ISSUE TITLE
Logo footer

### ISSUE THREAD

**Issue by NicoGonzalez94** [micaelacancino/DulceTentacion#25]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que al hacer click en el logo me redirija a la pagina principal.

## Resultado actual

• Al hacer click en el logo, este no redirige a ningun sitio.

## Captura

![image](https://github.com/user-attachments/assets/d5486d70-beea-426d-8367-0c07cb4ae38a)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by micaelacancino** [comment]
corrección realizada.
